name: Lint Code Base
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
